### ISSUE TITLE
Security issue with 123 sheets

### ISSUE THREAD

**Issue by mikemonteith** [hmrc/software-choices-frontend#100]
123sheets.co.uk is storing the Government Gateway ID and passwords of your users.
You should revoke their API access and stop listing them as a provider.
You should also force a password reset for any users who have given their password away to 123sheets.

Screenshot of 123sheets user information form.
![image](https://user-images.githubusercontent.com/227467/62688014-d847ff80-b9bf-11e9-8fac-11cd21bd995c.png)

I've tried to get in contact with HMRC support on twitter but not getting any reply so thought I'd try here.

**Comment by mikemonteith** [comment]
https://github.com/hmrc/software-choices-frontend/blob/master/conf/SoftwareProviders.json#L93

**Comment by mtd-api-team** [comment]
Hi @mikemonteith,

The appropriate HMRC areas are investigating this concern, and will contact the provider in question in due course.

You will appreciate that we can not discuss this further here.

Kind regards,

MTD API team

**Comment by mikemonteith** [comment]
@mtd-api-team understandable. Thanks for replying
